### ISSUE TITLE
Non-goal: analysis of HTTP Sig implementations

### ISSUE THREAD

**Issue by snarfed** [swicg/activitypub-http-signature#16]
Would be useful! But I'm inclined to avoid it here specifically, at least beyond their direct integrations into existing AP implementations.

**Comment by AaronNGray** [comment]
@snarfed I am sort of following along and looking at implementations. If you don't mind I would like to create a list of http-signature implementations used both by ActivityPub implementations and otherwise in a range of languages, JavaScript, Rust etc, ... . Ideally I would do this in a separate lone issue ?

**Comment by snarfed** [comment]
@AaronNGray sure, go for it! Agreed, probably separate issue.
