### ISSUE TITLE
Survey of HTTP Sig support in top fediverse servers

### ISSUE THREAD

**Issue by snarfed** [swicg/activitypub-http-signature#17]
It'd be nice to know, of the top 10 or 20 fediverse servers (eg by users), which HTTP Sig (and maybe LD Sig) versions do they emit and support incoming, do they support authorized fetch, etc. This could turn into a tar pit fast, so less is more here!

**Comment by mediaformat** [comment]
@vpzomtrrfrt created a handy comparison chart at https://arewehs2019yet.vpzom.click/, 
This is also mirrored at https://fedidevs.org/reference/signatures/

**Comment by snarfed** [comment]
Thanks! That table is great, good call.

**Comment by snarfed** [comment]
I'm reconsidering this a bit. Which projects send and accept which versions is obviously a moving target, and https://arewehs2019yet.vpzom.click/ is already tracking that ongoing, so I don't know how useful it would be to include a static snapshot in the report that will quickly go out of date.

Same with which projects support authorized fetch, but maybe that would be more useful if there isn't already a project tracking it?

**Comment by snarfed** [comment]
Initial draft text below. Please review!

---

[vpzom](https://vpzom.click/)'s [Are We HS2019 Yet?](https://arewehs2019yet.vpzom.click/) web site faithfully tracks HTTP Signature support in popular fediverse server projects over time. As of 2024-03-16, it covers 14 projects, including 8 of the top 10 projects by total registered users, and the 14 together cover 94% of registered users, 94% of MAUs, and 63% of instances in the fediverse. (Based on [https://fedidb.org/software](https://fedidb.org/software) and [https://fediverse.observer/stats](https://fedidb.org/software).)

That site is updated regularly, so this report doesn't duplicate its contents, but here are a couple highlights.

* All 14 projects support HTTP Signatures, both generating and sending them in outbound AP HTTP requests and validating signatures on incoming AP HTTP requests that include them.

* Very few projects share implementation code. PeerTube and Misskey both use [@peertube/http-signature](https://www.npmjs.com/package/@peertube/http-signature), Pleroma and Mobilizon both use [pleroma/http_signatures](https://git.pleroma.social/pleroma/elixir-libraries/http_signatures), and the rest all use their own implementations.

* All but one project support the `hs2019` placeholder algorithm in at least some form. This is a good sign that the fediverse is gradually advancing the version(s) of HTTP Signatures it supports, but getting past [cavage-12](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures) will take more work.

**Comment by snarfed** [comment]
micro.blog and the WordPress AP plugin are two projects notably absent from https://arewehs2019yet.vpzom.click/ that I'd like to include. I've asked them both, and I'll include their answers.

**Comment by snarfed** [comment]
Confirmed, both micro.blog and the WordPress plugin both send outgoing and verify incoming signatures.

**Comment by nightpool** [comment]
When you say "Mastodon is a big contributing factor here", what does that mean? I'm not really seeing anything in the vpzom survey that singles Mastodon out, it seems like every implementation is about the same or worse than Mastodon, and I'm not seeing any implementations that have significantly better compatibility (except for vpzom's own implementation, which only accounts for about .004% of users and about .01% of servers).

The problem of supporting newer versions doesn't feel like it's one that can be solved by naming and shaming individual implementations, we need some sort of better migration path that will let us upgrade servers that support new versions without breaking compatibility with older servers. Additionally, we need to come up with some sort of incentive to help encourage implementers to migrate, since the recent draft changes have created major breaking changes that require *substantial* rework of existing code, which has been a major concern among implementors (see e.g. https://github.com/TritonDataCenter/node-http-signature/issues/118 for an example). For example, parsing HTTP Signatures now requires a new, complicated RFC 8941 Structured Fields library, which may not exist for all languages. Adding more dependencies and moving the fediverse to a much more complicated signature scheme is going to raise the floor for new implementors also, so I think it's something we should consider carefully.

**Comment by snarfed** [comment]
@nightpool good points! You're right, I should probably remove that sentence entirely. I only mentioned it because of Mastodon's dominant position in the fediverse in terms of instances and user base, nothing beyond that, and I didn't really mean it to shame them particularly vs any other servers. But you're right, it's unnecesssary.

Beyond that, I also don't really plan to take a position in this report on the urgency of getting the fediverse overall to upgrade from cavage-12 to RFC9421. I generally want it to be more descriptive than prescriptive. So, another good reason to remove that sentence.
