### ISSUE TITLE
Another attempt to compile and standardize HTTP Signature usage in the Fediverse

### ISSUE THREAD

**Issue by perillamint** [swicg/activitypub-http-signature#19]
Hello, I'd like to notify that there is another attempt to compile and standardize HTTP signature usage in the Fediverse.

https://codeberg.org/aumetra/fep/src/branch/fep-e2ce/fep/e2ce/fep-e2ce.md

This proposal contains information that might be helpful to address issues  #1, #3, #4, #5, #7, #8, and #9.

We are open to discussing merging the effort between two attempts to standardize the HTTP signature usage in the Fediverse.

Note that this FEP is in DRAFT condition and does not cover the whole use case yet.

cc. @aumetra

**Comment by perillamint** [comment]
@nightpool Then, should I also post this on mailing list? Now, I honestly lost about how can we contribute our effort to swicg/activitypub-http-signature.

Where should we discuss it?

**Comment by evanp** [comment]
@perillamint it'd be great to get your contribution to this effort. I'm glad to see that there is a FEP process already happening. Since FEPs are CC0-licensed, I think the CG effort could use them as a source. Would you consider joining forces with @nightpool and @snarfed to get this important work finished? I agree with you, working together is great.

**Comment by aumetra** [comment]
Actually our work right now is CC-BY-SA licensed (as per the attribution of the linked file).  
We would love to collaborate on this to work out a good harmonic standard.

---

(To avoid confusion, I'm the co-author of the document linked by @perillamint )

**Comment by perillamint** [comment]
@evanp So, if you want us to contribute, we are willing to relicense our work to CC-BY or W3C CLA (AFAIK, CC-BY + Patent waiver) and start documenting background detail (why we decided to choose that decision, which AP implementations implement SHA-256 / other or broken digest implementation, etc.)

Also, if the answer is ok, how should we discuss this topic?

Should we sign up for the mailing list and discuss it there?
Or should we use this issue tracker?
Is a pull request accepted if we want to suggest changes directly?

Thanks.

**Comment by nightpool** [comment]
GitHub issues are a good place to start! Either by contributing to the
existing issues for individual sections or starting a new issue for topics
not yet covered.

With respect to pull requests, I defer to @snarfed, I don't know what the
best avenue for that looks like. We might not be at the point where that's
super useful yet without the general broad outline of the note in place.

**Comment by aumetra** [comment]
Added a few notes to already open issues

**Comment by snarfed** [comment]
Thank you @aumetra @perillamint! Comments on issues are great right now. We'll probably use issues to end up with the first pass at text for each section, and only then start filling in the report doc itself.

**Comment by snarfed** [comment]
@aumetra @perillamint thank you again for offering to help here! You all have obviously already done a ton of valuable work in FEP-e2ce. We'd love to join forces and reuse that instead of duplicating work.

I've sketched out a tentative outline for this report in #26. It looks like FEP-e2ce primarily focuses on section 3 there on detailed usage: generating keys, serving and reading them in actors, generating and verifying signatures. Would you all agree?

If so, one path forward could be for you all to take the lead there on section 3 specifically, see how much FEP-e2ce addresses its issues in #26, and fill in anything that's not already there. @nightpool and I could then focus on the other sections, with any contributions you all want to add.

Let me know what you think!

**Comment by evanp** [comment]
> If so, one path forward could be for you all to take the lead there on section 3 specifically, see how much FEP-e2ce addresses its issues in #26, and fill in anything that's not already there. @nightpool and I could then focus on the other sections, with any contributions you all want to add.

This is pretty great. It's worth noting that contributors to community group projects, like this report, need to sign the CLA:

https://www.w3.org/community/about/process/cla-deed/

It's how we tell the world that the standard is not patent encumbered, is royalty-free, etc.

It's part of the signup flow for the SocialCG:

https://www.w3.org/community/socialcg/

**Comment by snarfed** [comment]
@aumetra @perillamint friendly ping?

**Comment by aumetra** [comment]
Sorry, the notification went under in my inbox.

Yes, I agree, the FEP draft mostly focusses on the section 3 you defined, fetching, signing, etc.
I'd be okay with taking the lead together with perillamint on that section.

And I think @perillamint already signed the CLA, only I'm missing for now. So if they are also okay with this path forward, I'll get to signing the CLA.

**Comment by snarfed** [comment]
Awesome! Thank you both!

**Comment by snarfed** [comment]
@aumetra @perillamint just FYI I've been slowly filling in section 3 of #26. The checked off tasks there have draft text for the report. Feel free to review any of that text and/or fill in any unchecked tasks that don't yet have draft text!
