### ISSUE TITLE
Signed deletion requests from deleted users

### ISSUE THREAD

**Issue by edent** [swicg/activitypub-http-signature#25]
I've received an ActivityPub message saying a user has been deleted. It is signed:

```
Signature: keyId="https://opalstack.social/users/tlchomemobility#main-key",algorithm="rsa-sha256",headers="(request-target) host date digest content-type",signature="plMi+o/UUMbK95+4S1onnlwQNwZ0Jz4FXLTIYHlus8RcfxG32749GVrthpD0xwathkooYjsIR9e+e+EQwQwV1vGDCKq4VK/rmGjUHIkYU77F7e1Ih8lw+/F+0AoKP8FFa2wwWXNf8B4+i+uxdtBrdp1eRLHcB3qZIB3e4czkUNkJaEeygKJUn4pf5vy0hFvvHO8dNwjpz5n84B+aw+ZM0TfY/O+Hk6yB6vPgGwIwlR3Cq63dAzZXOVpinzhDmH6MfV1b/Jx2l5A4ytK1b24T0MSvEfsfEMNdHJgJ+WvPYaEyVSn1sn+7zvmmuVx4GwifYz/tRgpH3Xq9nMLvg9O/Cw=="
```

If I try to retrieve the keyId, I receive an HTTP 410 Gone. Because the user doesn't exist any more.

Should I accept this signature? I don't have their public key cached, so the verification process will fail.

**Comment by nightpool** [comment]
If you don't have their public key cached, then you shouldn't need to delete them :) 

Delete activities are only helpful for users that you already know about. However, this is a good reason for us to specify that you should always cache the public key of a user as soon as you become aware of them. 

Key rotations may mess this up for less-commonly-known actors—I think that's a good reason not to do them too frequently.

**Comment by nightpool** [comment]
Additionally, although this is outside of the scope of the HTTP Signatures spec, a 410 Gone is pretty much equivalent to a Delete action. So although I wouldn't delete an actor right away if I saw a 410 Gone, if I continued to see one after (a week? a month?) I would consider going ahead and deleting the actor.

**Comment by snarfed** [comment]
Thanks @nightpool! This is definitely a FAQ, we should document it in the AP Primer if it's not already there.

And key rotation is interesting. Hopefully an actor's instance will send `Update`s for the actor with the new key far and wide, but those inevitably won't get everywhere, and won't happen at all with blind key rotation. So yes, interpreting 410 Gone as `Delete` makes sense.

**Comment by snarfed** [comment]
First draft at text below. Please revise!

(I also don't know if we want to write in second person, ie with "you," or third person. I don't feel strongly, feel free to weigh in.)

---

When you [receive a `Delete` activity](https://www.w3.org/wiki/ActivityPub/Primer/Delete_activity), you should first attempt to verify its HTTP Signature, as with any activity. If you don't have the signing actor's public key cached, or if the cached key doesn't match the signature, you should fetch the actor and retry. If that fetch returns HTTP 410 Gone, you can interpret the `Delete` as valid and delete your local cache of the actor, if any.

**Comment by edent** [comment]
Judging by the way things are written on https://www.w3.org/wiki/ActivityPub/Primer/Delete_activity, I'd tweak the wording a bit.

When a `Delete` activity is received, it is important to verify the request's HTTP Message Signature:
* Check if the cached public key matches the signature. If it does, the `Delete` activity can be processed.
* If the cached public key does not match the signature, or there is no cached public key, the actor's public key should be fetched.
* Check if the response is an HTTP 410 Gone or 404 Not Found. If it is, assume the user has been deleted from the server and interpret the `Delete` as valid and process it.
* If the public key was successfully retrieved, attempt to verify the signature.
* If the signature matches, the `Delete` activity can be processed.
* If the signature does not match, do not process the activity.

**Comment by snarfed** [comment]
@edent looks great, thank you!@

**Comment by nightpool** [comment]
I don't think "interpret the Delete as valid" is the right way to phrase
that. For example, if there was some sort of "deleted reason" or "deleted
by" metadata in the Delete activity, we shouldn't consider it as authorized
just because the whole account was deleted. I would say "If the response
matches HTTP 410 Gone, then you should stop processing the activity, but
understand that the actor has in fact been deleted. Best practices for
handling a deleted actor when you're not able to receive signed
confirmation of a Delete activity are available in the ActivityPub primer."
or something like that.

I would not recommend doing the same for a 404 result. There are too many
situations where a 404 result could be communicated erroneously or due to
server misconfiguration.

**Comment by snarfed** [comment]
Omitting 404 is a good point. And yes, we'd only want to interpret 410 as the actor is deleted, nothing more, but I'd be curious to hear a concrete example of something else in a `Delete` activity that could have some side effect or other meaning that we wouldn't want to process. Can't think of one off the top of my head. Regardless, true.

**Comment by argrath** [comment]
I think it's more natural that an activity deleting an actor is signed by the instance actor.

**Comment by snarfed** [comment]
Thanks all! I've added this in a new section, https://swicg.github.io/activitypub-http-signature/#handling-deletes-of-actors .

@argrath, re signing with the instance actor, that does seems like a good idea! The problem is that there's no standard way to distinguish an instance actor from any other actor. So if we can't always determine that for sure, we can't know whether the signing actor is authorized to delete a different actor on the same server.
