### ISSUE TITLE
Identify the signature algorithms used

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#3]
I've only seen RSA; maybe there are others that are actually supported?

**Comment by nightpool** [comment]
Supporting Ed25519 is a common request on the Mastodon github. However, there are a few thorny key confusion and signature algorithm confusion issues to sort through first (storing some kind of key metadata in the database alongside the PEM), and it's not clear that the extra complexity is worth it.

One benefit is that it would probably be easier/less code to support a new non-PEM container format for a new key algorithm then it would be to support the full matrix of (2x key algorithms) x (2x container formats), and everyone hates having to deal with PEM containers.

**Comment by aumetra** [comment]
[Kitsune supports Ed25519](https://github.com/kitsune-soc/kitsune/blob/241eca91ad45dca173558f2a9cffc45a7a4c403f/kitsune/src/http/extractor/signed_activity.rs#L131-L136) and it is *not* a problem. Key confusion attacks here aren't really applicable either since key confusion pretty much means "I'm implementing a symmetric algorithm and my API is kinda bad".  

You can identify the key via the `AlgorithmIdentifier` field in the PKCS#8 payload and then pass it to the appropriate decoder for the key (since PKCS#8 is pretty much just `algorithm tag + some bytes which represent the key somehow`).

Key confusion would imply that the attacker would somehow be able to forge a correct looking signature which wouldn't really be possible if you only allow Ed25519 or RSA (or any other asymmetric signature scheme for that matter).  
Key confusion would only become an issue once you start supporting things like HMAC or BLAKE2 in MAC mode (or tagged BLAKE3, etc.), which would allow the attacker to sign the payload using the public key as the key and confusing the implementation into following the symmetric verification path.

Since this isn't really something you can do when properly restricting the algorithms (as seen in the Kitsune source, supporting Ed25519 (or even ECDSA, even though why would you?)) is a non-issue.

**Comment by perillamint** [comment]
I also think supporting symmetric signing in the Fediverse is not sound. I think it should be prohibited per specification, as @aumetra said.

We basically do not have any sound way to transfer shared secrets from one instance to another, so we can safely disable the HMAC family from the `cavage` draft. Also, adequately implemented RSA/EdDSA implementation that accepts PKCS#8 will reject the wrong key type when they are implemented correctly. (if it confuses the key, it means the implementation is horribly broken)

**Comment by snarfed** [comment]
Incorporating into #33.
