### ISSUE TITLE
Who may delete an actor? Or any object?

### ISSUE THREAD

**Issue by jernst** [swicg/activitypub-http-signature#55]
In "3.3 Handling Deletes of actors" it says:

> If the signature's `keyId` doesn't match the `Delete`'s `object` or its server's [3.2 Instance actor](https://swicg.github.io/activitypub-http-signature/#instance-actor), discard the `Delete` and do not process it.

In the first case, it sounds like the object == actor == the owner of the key used for the signature. The actor deletes themselves, fine.

In the second case, it sounds like the object != actor == the owner of the key used for the signature == the instance actor. The instance actor deletes an actor on their server, also probably fine.

What about moderators who act under their own key pair? Do they get to delete actors? How can a receiver know?

Perhaps this is a broader question than just about actors: who may delete a object that's not owned by themselves? How does a receiver of a Delete message make the correct decision on whether to process it?

**Comment by snarfed** [comment]
Right! This is authorization/access control, [which is a non-goal here](https://swicg.github.io/activitypub-http-signature/#non-goals), and woefully incomplete in the spec(s)...but to answer the question, Deletes and other activities that modify other objects and activities generally need to have the same actor as the original object's `attributedTo` or activity's actor. More in https://www.w3.org/wiki/ActivityPub/Primer/Authentication_Authorization#Object_ownership and https://www.w3.org/wiki/ActivityPub/Primer/Authentication_Authorization#Actor_ownership

Servers can let moderators delete or otherwise modify existing objects and activities, of course, but they generally need to federate those modification activities using the original actor.

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen!
