### ISSUE TITLE
Describe how to transform a key id into a public key

### ISSUE THREAD

**Issue by evanp** [swicg/activitypub-http-signature#8]
I think the steps are:

If there's a fragment...

- fetch the resource at the HTTPS URL
- look for a property with the same name as the fragment
- get the publicKeyPem of that property

If there's no fragment...

- fetch the resource at the HTTPS URL
- get the publicKeyPem of that object

**Comment by nightpool** [comment]
In practice, the actual algorithm that's used is "Fetch the keyId, check to see if you've been shown an ActivityPub actor, then throw away the key ID and use the key specified in the ActivityPub actor". 

The fragment is more of a fig-leaf. I *think* this is a fine approach conceptually given the modern HTTP Signatures recommendation that key metadata should be exchanged out-of-channel, but the implementation leaves something to be desired.

**Comment by mro** [comment]
https://www.w3.org/wiki/SocialCG/ActivityPub/Authentication_Authorization#Signing_requests_using_HTTP_Signatures says "The [keyId](https://tools.ietf.org/html/draft-cavage-http-signatures-08#section-2.1.1) should link to the actor so that the publicKey field can be retrieved."

that's the end of a bit a rat's tail as summarized in https://blog.mro.name/2023/12/implementing-federation-i/#fnref:http-sign and originating in https://www.w3.org/TR/activitypub/#authorization

**Comment by evanp** [comment]
Mastodon, at least, will treat a keyId with a fragment as an actor, and a keyId with no fragment as going directly to the publicKey object.

**Comment by evanp** [comment]
I'll also say that having a keyId that points to an actual key is conceptually so, so much better than one that points to an actor.

**Comment by snarfed** [comment]
Ugh. I still really don't understand fragment handling expectations here, or in general. I'm inclined to a) lean on @nightpool's expertise for this bit, b) aggressively limit how much we get into details and options here, especially ones that we don't see meaningfully in the wild, and c) say that discussing fragment handling and resolution specifically is a non-goal for this report.

Feedback and counterarguments welcome. 😎

**Comment by nightpool** [comment]
> Mastodon, at least, will treat a keyId with a fragment as an actor, and a keyId with no fragment as going directly to the publicKey object.

I'm pretty sure this is incorrect. At no point in the key resolution algorithm is the fragment considered. The logic is as I described it, although you're correct that there's an additional element for if the keyid points to the PublicKey object directly with no fragment—in that case we have to make an additional HTTP request to the `actor` URL to make sure that the public key object is authorized (by comparing the URI we resolved to the URI of the publicKeyt property of the actor object)

**Comment by snarfed** [comment]
> in that case we have to make an additional HTTP request to the `actor` URL to make sure that the public key object is authorized

@nightpool did you mean `controller` URL? I'm putting together the initial draft text here, and [looking at the LD Security vocab `Key` object](https://w3c-ccg.github.io/security-vocab/#Key), it [has `controller`](https://w3c-ccg.github.io/security-vocab/#controller) but not `actor`.

**Comment by snarfed** [comment]
Initial draft text for this and #8 below. Please review and revise!

---

Here's how to find the public key to use to verify a fediverse HTTP Signature:

1. Extract the signature's [`keyId` parameter](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12#section-2.1.1). It should be a URL. If it has a fragment, discard it.
1. If you cache remote ActivityPub objects locally, look up the object with that id in your local store.
1. If you don't have it locally, fetch it.
1. If it's an [ActivityStreams 2 actor](https://www.w3.org/TR/activitystreams-core/#actors), the PEM-encoded public key will be in the `publicKey.publicKeyPem` property. This is based on the [LD Security Vocabulary](https://w3c-ccg.github.io/security-vocab/#publicKey).
1. If it's a raw [LD Security `Key` object](https://w3c-ccg.github.io/security-vocab/#Key), use its `controller` property as the new key id, jump back to step 2, and repeat.
1. Otherwise, the key can't be fetched at this time, and the signature verification fails.

Note that the current [LD Security Vocabulary](https://w3c-ccg.github.io/security-vocab/#publicKey) only supports a single public key per actor. [FEP-521a](https://codeberg.org/fediverse/fep/src/branch/main/fep/521a/fep-521a.md) describes an extension to support multiple keys per actor, but it's not yet widely supported in the fediverse.
